version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=isi_backend_assessment_test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  tabungan-api:
    build:
      context: ./tabungan-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=localhost
      - PORT=3000
      - DB_DRIVER=postgres
      - DB_SOURCE=postgresql://root:secret@localhost:5432/isi_backend_assessment_test?sslmode=disable
    depends_on:
      - postgres

volumes:
  postgres-data:
