// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: customers.sql

package sqlc

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    nama,
    nik,
    no_hp
) VALUES (
    $1, $2, $3
) RETURNING created_at, id, nama, nik, no_hp
`

type CreateCustomerParams struct {
	Nama string `json:"nama"`
	Nik  string `json:"nik"`
	NoHp string `json:"no_hp"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer, arg.Nama, arg.Nik, arg.NoHp)
	var i Customer
	err := row.Scan(
		&i.CreatedAt,
		&i.ID,
		&i.Nama,
		&i.Nik,
		&i.NoHp,
	)
	return i, err
}
