// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: entries.sql

package sqlc

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
    no_rekening,
    nominal,
    type_id
) VALUES (
    $1, $2, $3
) RETURNING no_rekening, nominal, created_at, id, type_id
`

type CreateEntryParams struct {
	NoRekening string `json:"no_rekening"`
	Nominal    int64  `json:"nominal"`
	TypeID     string `json:"type_id"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.NoRekening, arg.Nominal, arg.TypeID)
	var i Entry
	err := row.Scan(
		&i.NoRekening,
		&i.Nominal,
		&i.CreatedAt,
		&i.ID,
		&i.TypeID,
	)
	return i, err
}

const getEntries = `-- name: GetEntries :many
SELECT no_rekening, nominal, created_at, id, type_id FROM entries 
WHERE no_rekening = $1
ORDER BY created_at
`

func (q *Queries) GetEntries(ctx context.Context, noRekening string) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getEntries, noRekening)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.NoRekening,
			&i.Nominal,
			&i.CreatedAt,
			&i.ID,
			&i.TypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
