// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"time"
)

type Account struct {
	CreatedAt  time.Time `json:"created_at"`
	CustomerID int64     `json:"customer_id"`
	NoRekening string    `json:"no_rekening"`
	Saldo      int64     `json:"saldo"`
}

type Customer struct {
	CreatedAt time.Time `json:"created_at"`
	ID        int64     `json:"id"`
	Nama      string    `json:"nama"`
	Nik       string    `json:"nik"`
	NoHp      string    `json:"no_hp"`
}

type Entry struct {
	NoRekening string `json:"no_rekening"`
	// can be negative or positive
	Nominal   int64     `json:"nominal"`
	CreatedAt time.Time `json:"created_at"`
	ID        int64     `json:"id"`
	TypeID    string    `json:"type_id"`
}

// init it with types of DEPOSIT, WITHDRAWAL
type EntryType struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
