// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	GetAccount(ctx context.Context, noRekening string) (Account, error)
	GetEntries(ctx context.Context, noRekening string) ([]Entry, error)
	UpdateSaldo(ctx context.Context, arg UpdateSaldoParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
